services:

  db:
    image: postgres:latest
    container_name: videoflix_database
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: videoflix_redis
    restart: always
    volumes:
      - redis_data:/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    container_name: videoflix_backend
    restart: always
    volumes:
      - ${DOCKER_VOLUME}
      - videoflix_media:/app/media
      - videoflix_static:/app/static
    depends_on:
      - db
      - redis
    logging:
      options:
        max-size: "10m"
        max-file: "3"




volumes:
  postgres_data:
  redis_data:
  videoflix_media:
  videoflix_static:
