services:

  db:
    restart: always
    logging: 
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  web:
    entrypoint: ["/app/backend.entrypoint.prod.sh"]
    volumes:
      - /srv/videoflix/media:/app/media
      - /srv/videoflix/static:/app/static
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: videoflix_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/videoflix/static:/srv/videoflix/static
      - /srv/videoflix/media:/srv/videoflix/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web
  
  worker:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: videoflix_worker
    entrypoint: ""
    command: python manage.py rqworker default
    env_file: .env
    volumes:
      - /srv/videoflix/media:/app/media
      - /srv/videoflix/static:/app/static
    depends_on:
      - redis
    restart: always

  certbot:
    image: certbot/certbot
    container_name: videoflix_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
