services:

  web:
    entrypoint: ["/app/backend.entrypoint.dev.sh"]
    volumes:
      - .:/app
      - videoflix_media:/app/media
      - videoflix_static:/app/static
    ports:
      - "8000:8000"
