# Generated by Django 5.2.4 on 2025-08-11 14:12

import utils.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.videos.video_upload_to),
        ),
    ]
