# Generated by Django 5.2.4 on 2025-08-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_video_duration_seconds_video_file_size_mb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchprogress',
            name='resolution',
            field=models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=10),
        ),
        migrations.AlterField(
            model_name='videostreamvariant',
            name='resolution',
            field=models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=10),
        ),
    ]
